"""notifications

Revision ID: 02c84fed75ee
Revises: 5b15b334a118
Create Date: 2025-02-14 01:15:09.594076

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '02c84fed75ee'
down_revision = '5b15b334a118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=128), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('timestamp', sa.Float(), nullable=False),
                    sa.Column('payload_json', sa.Text(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_notifications_user_id_user')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
                    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_timestamp'))
        batch_op.drop_index(batch_op.f('ix_notifications_name'))

    op.drop_table('notifications')
    # ### end Alembic commands ###
