"""updated Notifications table name

Revision ID: 0768bc299174
Revises: 02c84fed75ee
Create Date: 2025-02-14 01:17:52.512631

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0768bc299174'
down_revision = '02c84fed75ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=128), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('timestamp', sa.Float(), nullable=False),
                    sa.Column('payload_json', sa.Text(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_notification_user_id_user')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
                    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_name')
        batch_op.drop_index('ix_notifications_timestamp')
        batch_op.drop_index('ix_notifications_user_id')

    op.drop_table('notifications')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
                    sa.Column('user_id', sa.INTEGER(), nullable=False),
                    sa.Column('timestamp', sa.FLOAT(), nullable=False),
                    sa.Column('payload_json', sa.TEXT(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_notifications_user_id_user'),
                    sa.PrimaryKeyConstraint('id', name='pk_notifications')
                    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_notifications_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_notifications_name', ['name'], unique=False)

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_timestamp'))
        batch_op.drop_index(batch_op.f('ix_notification_name'))

    op.drop_table('notification')
    # ### end Alembic commands ###
