"""revert timestamp column in Notifications table

Revision ID: 66138884e5be
Revises: 104c5c948b8b
Create Date: 2025-02-17 01:15:59.163402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66138884e5be'
down_revision = '104c5c948b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.Float(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
