"""add followers

Revision ID: 7bd760090d16
Revises: e12a221bdaa5
Create Date: 2025-02-02 19:46:44.249957

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7bd760090d16'
down_revision = 'e12a221bdaa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
                    sa.Column('follower_id', mysql.INTEGER(), nullable=False),
                    sa.Column('followed_id', mysql.INTEGER(), nullable=False),
                    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], name=op.f('fk_followers_followed_id_user')),
                    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], name=op.f('fk_followers_follower_id_user')),
                    sa.PrimaryKeyConstraint('follower_id', 'followed_id', name=op.f('pk_followers'))
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
