"""private messages

Revision ID: 92787850b371
Revises: e07b0dce21be
Create Date: 2025-02-14 00:43:11.726201

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '92787850b371'
down_revision = 'e07b0dce21be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('sender_id', sa.Integer(), nullable=False),
                    sa.Column('recipient_id', sa.Integer(), nullable=False),
                    sa.Column('body', sa.String(length=140), nullable=False),
                    sa.Column('timestamp', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], name=op.f('fk_message_recipient_id_user')),
                    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name=op.f('fk_message_sender_id_user')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_message'))
                    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_timestamp'))
        batch_op.drop_index(batch_op.f('ix_message_sender_id'))
        batch_op.drop_index(batch_op.f('ix_message_recipient_id'))

    op.drop_table('message')
    # ### end Alembic commands ###
